# Generated by Django 5.2.15 on 2026-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibicion',
            name='tematica',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
